#6 Implemented the endpoint to get all orders with filters
joao-silva1007/mindera-pizza pull request #11
Opened 2022-08-31 10:39 UTC by joao-silva1007

Finds and returns an array of RestaurantOrder objects based on filters.

The current filters implemented are:

- Client's name
- Client's phone number
- Client's VAT number
- Order's current status

2022-08-31 14:41 UTC, jflora91 requested changes

2022-08-31 14:41 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/order/RestaurantOrderService.java
> +            if (currentSpec != null) spec = spec.and(currentSpec);
convém ser consistente, se normalmente usas a estrutura de colocar '{' e '}' nas condições de if, for, etc é bom manter os {}

2022-08-31 14:41 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +        Client c = new Client("name", "email@gmail.com");
no java 10 temos uma nova keyword "var" e da biblioteca lombok o "val" acho que podes usar

2022-08-31 14:41 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +        Client c = new Client("name", "email@gmail.com");
existem aqui dados que foram criados no teste anterior, não daria para fazer merge dos 2 em vez de repetir?

2022-08-31 14:41 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +        Client c = new Client("name", "email@gmail.com");
outra forma de criares um client seria de usares o Builder, podes dar um check

2022-08-31 14:41 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +    void getOrdersWithVatNumber() {
nesta classe de testes o que estás a testar/validar mesmo?

2022-08-31 14:41 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTestIT.java
> +        RestaurantOrder ro1 = new RestaurantOrder(LocalDateTime.of(2022,4,10,10,10,10),addressRepo.findById(1L).orElseThrow(), clientRepo.findById(1L).orElseThrow());
esta linha precisa de umas quebras, normalmente tenho o meu ide a marcar os 120 caracteres, facilita na leitura

2022-08-31 14:41 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTestIT.java
> +        RestaurantOrder ro1 = new RestaurantOrder(LocalDateTime.of(2022,4,10,10,10,10),addressRepo.findById(1L).orElseThrow(), clientRepo.findById(1L).orElseThrow());
para tornar mais clean podes definir propriedades localDateTime, address e client estática e depois reutilizar para cada restaurantOrder, evitas assim que sempre que cries um novo objecto restaurantOrder tenhas de criar um novo objecto localdatetime e 2 finds aos repositorios

2022-08-31 15:32 UTC, joao-silva1007 commented on src/main/java/com/mindera/pizza/configurations/DatabaseBootstrapper.java
> +            c.setPhoneNumber("912345678");
deixei só porque os endpoints para os clients, addresses, etc ainda não estão criados, então assim conseguia testar os endpoints que estava a fazer no postman sem ter de criar os objetos manualmente

2022-08-31 15:42 UTC, joao-silva1007 commented on src/main/java/com/mindera/pizza/domain/order/OrderStatus.java
> +            return null;
eu fiz isto assim para poder usar no RestaurantOrderSpecifications sem me dar throw a exceção, se fizesse a conversão para OrderStatus no service ia ter de converter de Object para String ou OrderStatus, foi só para simplificar o método

2022-08-31 16:11 UTC, joao-silva1007 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +    void getOrdersWithVatNumber() {
estava a testar o controller de forma isolada, sei que não há muito para testar porque os métodos são simples mas era só para ser consistente

2022-09-01 13:54 UTC, jflora91 requested changes

2022-09-01 13:54 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +    static void beforeAll() {
nice 👍

2022-09-01 13:54 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +    void getOrdersWithVatNumber() {
pois exato, era aí que queria chegar, se não está a ser testado nada efetivamente, existe a necessidade de criar um teste para isso?
não seria mais fiável fazer se calhar aqui um teste ponto-a-ponto do estilo mock mvc que tens feito para os outros endpoints? assim sempre testavas se efetivamente o endpoint está a ir buscar o que é expectavel à bd

2022-09-01 14:04 UTC, jflora91 commented on src/main/java/com/mindera/pizza/configurations/DatabaseBootstrapper.java
> +            c.setPhoneNumber("912345678");
não ficaria mais clean (e não poluia tanto o código) se criasses um ficheiro sql que escreve-se na BD sempre arrancasses? assim quando terminasses esses teste "live" era só remover o ficheiro, é só um exemplo

2022-09-01 14:08 UTC, jflora91 commented
outra coisa que acho importante de implementar no teu código, a criação de logs. Para ajudar na visualização do comportamento do teu serviço seria importante ter algum output do serviço para saber o que realmente está a acontecer em background.
* logs a informar de que um client foi criado e guardado
* logs mais explícitos de quando algo de errado ocorre (problema a guardar um address sem relação)
* logs de quando encomenda atualiza o seu status
* etc
pode ser-te útil dar um check no logback, log4j

2022-09-01 14:14 UTC, joao-silva1007 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +    void getOrdersWithVatNumber() {
sim eu tenho os dois, estes testes em especifico era só para isolar o controller mas posso apagar realmente, não acrescentam muito

2022-09-01 14:16 UTC, joao-silva1007 commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTestIT.java
> -        assertTrue(restaurantOrderRepo.findAll().isEmpty());
Porque antes estava a apagar as restaurantOrders todas antes de correr os testes, agora existem sempre pelo menos 3 e dependendo da ordem de execução dos testes podem haver 4, não tenho uma maneira de fazer um assert pelo numero de registos, só se fizesse um find no inicio do teste e um no final e comparasse o tamanho das listas

2022-09-02 09:48 UTC, jflora91 approved these changes

2022-09-02 09:49 UTC, merged