12 update an orders status
joao-silva1007/mindera-pizza pull request #15
Opened 2022-09-02 15:03 UTC by joao-silva1007

Implemented an endpoint that, given a restaurant's order ID, changes an order status to:

- FINISHED
- ACCEPTED
- CANCELED

2022-09-05 08:02 UTC, jflora91 requested changes

2022-09-05 08:02 UTC, jflora91 commented on src/test/java/com/mindera/pizza/services/order/RestaurantOrderServiceTest.java
> +        RestaurantOrder expectedRo = new RestaurantOrder(LocalDateTime.of(2021,10,10,10,10,10),a, c);
há aqui 2 ou 3 linhas que se repetem em todos os testes

2022-09-06 09:44 UTC, jflora91 requested changes

2022-09-06 09:44 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/DatabaseTimestamps.java
> +    @PreUpdate
nice nice

2022-09-06 09:44 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/address/Address.java
> +    private final DatabaseTimestamps timestamps = new DatabaseTimestamps();
solução porreira para adicionares o created e updated mas não bastaria fazer o extend da class?

2022-09-06 09:44 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/order/RestaurantOrder.java
> +            throw new InvalidStatusChangeException(String.format(Errors.ILLEGAL_STATUS_CHANGE.toString(), this.currentStatus, OrderStatus.FINISHED));
pra simplificar a chamada desta excepção, não seria mais fácil enviares aqui como parametro o Errors.ILLEGAL_STATUS_CHANGE, this.currentStatus, OrderStatus.FINISHED e depois dentro da excepção tratavas do string.format? tornava mais limpo deste lado a chamada

2022-09-06 09:44 UTC, jflora91 commented on src/main/java/com/mindera/pizza/utils/Errors.java
> +public enum Errors {
boa abordagem

2022-09-06 10:33 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/address/Address.java
> +public class Address extends DatabaseTimestamps{
👍

2022-09-06 10:33 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/order/RestaurantOrderService.java
> +            case RECEIVED -> throw new InvalidStatusChangeException(Errors.ILLEGAL_STATUS_CHANGE_TO, OrderStatus.RECEIVED);
👍

2022-09-06 10:35 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/DatabaseTimestamps.java
> +public abstract class DatabaseTimestamps {
porque colocaste como classe abstrata?

2022-09-06 10:37 UTC, joao-silva1007 commented on src/main/java/com/mindera/pizza/domain/DatabaseTimestamps.java
> +public abstract class DatabaseTimestamps {
porque nunca pode haver uma instância dessa classe neste caso, só podem haver instâncias das subclasses

2022-09-07 08:24 UTC, jflora91 approved these changes

2022-09-07 08:34 UTC, merged