#18 Implemented endpoint to create a category
joao-silva1007/mindera-pizza pull request #19
Opened 2022-09-02 16:10 UTC by joao-silva1007

Implemented controller and service methods to create a category.
Implemented tests of the previous methods

2022-09-05 08:27 UTC, jflora91 requested changes

2022-09-05 08:27 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/category/CategoryService.java
> +        return categoryRepo.save(category);
é correto existirem categorias com o mesmo nome?

2022-09-05 08:27 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/category/CategoryControllerIT.java
> +        categoryRepo.deleteById((long) id);
não poderias criar um método anotado com o beforeeach ou beforeall para limpar sempre a base de dados após a execução de cada teste?

2022-09-05 13:32 UTC, joao-silva1007 commented on src/test/java/com/mindera/pizza/controllers/category/CategoryControllerIT.java
> +        categoryRepo.deleteById((long) id);
Da maneira que os testes da RestaurantOrder estao feitos é preciso haver categorias antes, tenho que alterar os outros testes para acrescentar isso

2022-09-06 09:46 UTC, jflora91 requested changes

2022-09-06 09:46 UTC, jflora91 commented on src/test/java/com/mindera/pizza/PizzaApplicationTests.java
> +	/*@Test
ficou esquecido?
convem fazer um teste pra validar a condição de ser único, que mensagem de erro é retornada?

2022-09-07 08:26 UTC, jflora91 requested changes

2022-09-07 08:26 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/category/CategoryService.java
> +            throw new DataIntegrityViolationException("A Category already exists with the inserted name");
não criaste um enum para guardar as mensagens de erro?

2022-09-07 08:28 UTC, joao-silva1007 commented on src/main/java/com/mindera/pizza/services/category/CategoryService.java
> +            throw new DataIntegrityViolationException("A Category already exists with the inserted name");
estavam no outro branch, vou dar merge e meto aqui

2022-09-07 09:17 UTC, merged