#30 Create/Get/GetById ingredients
joao-silva1007/mindera-pizza pull request #35
Opened 2022-09-07 11:59 UTC by joao-silva1007

Implemented all methods and tests for creating/getting/gettingById of an ingredient

2022-09-07 13:31 UTC, jflora91 requested changes

2022-09-07 13:31 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/ingredient/Ingredient.java
>          if (name.isBlank()) {
existem anotações @null @empty @valid, etc... para associar às propriedades que pode substituir estas validações quando estás a receber a informação sobre ingredientes no endpoint de create

2022-09-07 13:31 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/ingredient/Ingredient.java
> +    @Builder
esta anotação não devia ficar associado à class?

2022-09-07 13:31 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/ingredient/Ingredient.java
> +    @Builder
e assim não precisas de fazer o this.name=name, ...

2022-09-07 13:31 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/ingredient/IngredientControllerIT.java
> +                        .content(mapper.writeValueAsString(new CreateIngredientDTO("Pepperoni", 10))))
anotando a class CreateIngredientDTO com @Builder podes criar o objecto mas de forma mais correta

2022-09-07 13:31 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/ingredient/IngredientService.java
> +        Ingredient ingredient = Ingredient.builder()
para simplificar a conversão entre objectos DTO para objectos do tipo entidade podias optar pela criação de uma classe de conversão e essa classe sim fazer o mapeamento entre classes. Existem vários tipos e estratégias, costumamos usar uma do Orika (MapperFactory).
Isto para não deixar do lado do service a responsabilidade de mapeamento

2022-09-07 13:31 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/ingredient/IngredientService.java
> +                .orElseThrow(() -> new DatabaseEntryNotFoundException(String.format(Errors.ENTRY_BY_ID_NOT_FOUND.toString(), Ingredient.class.getSimpleName())));
a mesma questão de num dos ultimos PRs, deixar o String.format do lado da excepção

2022-09-07 13:31 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/ingredient/IngredientService.java
> +    public List<Ingredient> getIngredients(String ingredientName) {
porque retornas uma lista de ingredients? não existe outra collection que seria mais correta?

2022-09-07 13:31 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/ingredient/IngredientControllerIT.java
> +    static void beforeAll(@Autowired IngredientRepo ingredientRepo) {
porque envias por parametro o ingredientRepo?

2022-09-07 13:31 UTC, jflora91 commented on src/test/java/com/mindera/pizza/controllers/ingredient/IngredientControllerIT.java
> +    static void afterAll(@Autowired IngredientRepo ingredientRepo) {
porque envias por parametro o ingredientRepo?

2022-09-07 13:31 UTC, jflora91 commented on src/main/java/com/mindera/pizza/utils/LoggingMessages.java
> +    UNIQUE_ENTRY_VIOLATION("Attempted to create a {} with an existing {} ({})"),
estas 2 estão a ser usadas em algum lado?

2022-09-07 13:41 UTC, joao-silva1007 commented on src/test/java/com/mindera/pizza/controllers/ingredient/IngredientControllerIT.java
> +    static void afterAll(@Autowired IngredientRepo ingredientRepo) {
como o afterAll é static não consigo usar o objeto que dou autowire na classe, e se definir o objeto como static não consigo dar autowire

2022-09-07 13:41 UTC, joao-silva1007 commented on src/test/java/com/mindera/pizza/controllers/ingredient/IngredientControllerIT.java
> +    static void beforeAll(@Autowired IngredientRepo ingredientRepo) {
como o afterAll é static não consigo usar o objeto que dou autowire na classe, e se definir o objeto como static não consigo dar autowire

2022-09-09 08:40 UTC, jflora91 requested changes

2022-09-09 08:40 UTC, jflora91 commented on pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
porque não definiste a versão nesta dependência?

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/address/Address.java
>      public Address(String streetName, int streetNumber, String zipCode, String city, String nickname, Client client) {
com a anotação de builder anotada na classe não precisas de criar este construtor

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/category/Category.java
>      @Builder
o mesmo do comentario anterior

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/client/Client.java
> +    @Pattern(regexp = "[0-9]{9}", message = DataValidationConstants.INVALID_VAT_NUMBER)
e pro caso de contribuintes doutro formatos de pessoas não portuguesas?

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/client/Client.java
> +    @Pattern(regexp = "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\
este regex é complexo, o que faz mesmo?

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/ingredient/Ingredient.java
> +    @Builder
e qual o problema disso? estás a expor uma ação que vai ser usada por ti, só não tens de chamar no builder as propriedades que não queres.
neste caso com este construtor podes até criar um objecto sem definir o id mas depois podes fazer o set do id, indiretamente essa propriedade fica exposta também

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/domain/address/Address.java
> +    @NotBlank(message = DataValidationConstants.INVALID_STREET_NAME)
temos 2 dominios de classes, "dto" e "domain"
sendo que a informação que vem do exterior "passa" primeiro pela classes dto não seria melhor alocar estas validações no objeto de entrada? se levantar incoerencias, levanta logo no início e não na fase quando já vai para guardar na BD

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/mappers/category/CategoryMapper.java
> +public class CategoryMapper {
👍

2022-09-09 08:40 UTC, jflora91 commented on src/main/java/com/mindera/pizza/services/category/CategoryService.java
> +        Category category = CategoryMapper.convertToDomain(categoryDTO);
noice

2022-09-09 09:41 UTC, joao-silva1007 commented on src/main/java/com/mindera/pizza/domain/client/Client.java
> +    @Pattern(regexp = "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\
eu já tinha usado isso antes https://emailregex.com/, foi para não ter de definir um regex novo que podia falhar em alguns casos

2022-09-09 13:53 UTC, jflora91 approved these changes

2022-09-09 15:35 UTC, merged