4 create a new order
joao-silva1007/mindera-pizza pull request #9
Opened 2022-08-19 11:38 UTC by joao-silva1007

Implemented service and controller methods to create a new restaurant order.
Implemented unit tests for the previous methods.
Updated the RestaurantOrder entity to update the total price when a new product is added.

2022-08-19 13:15 UTC, alexsrosa requested changes

2022-08-19 13:15 UTC, alexsrosa commented on src/main/java/com/mindera/pizza/services/order/RestaurantOrderService.java
> +        for (Product product : products) {
gostava de ver isso com stream, experimenta para ver se fica mais clean

2022-08-19 13:15 UTC, alexsrosa commented on src/test/java/com/mindera/pizza/controllers/order/RestaurantOrderControllerTest.java
> +class RestaurantOrderControllerTest {
notei que fizestes testes muitos simples e somente unitários. Experimenta algo mais completo e integrado, o spring tem cenas muito fixes. segue uma página com exemplo e para teres algumas ideias 
https://www.baeldung.com/spring-boot-testing

2022-08-19 14:26 UTC, joao-silva1007 commented on src/main/java/com/mindera/pizza/exceptions/GlobalExceptionHandler.java
> +    private Map<String, String> getExceptionBody(Exception e, HttpStatus status) {
Acho que fiz as alterações que recomendaste, mas posso ter entendido mal. Se faltar alguma coisa avisa-me 😄

2022-08-30 09:12 UTC, alexsrosa commented on src/main/java/com/mindera/pizza/PizzaApplication.java
> +			Client c = new Client("name1", "email@gmail.com");
OK, neste caso sempre deixa um TODO no codigo para que for ler enteder a necessidade temporaria.

2022-08-30 09:18 UTC, alexsrosa commented on src/main/java/com/mindera/pizza/exceptions/GlobalExceptionHandler.java
> +    private Map<String, String> getExceptionBody(Exception e, HttpStatus status) {
Na linha 15 estas a retornar um objeto do tipo ResponseEntity<Object>, mas poderia criar um objeto que representa o teu map. Exemplo: ResponseDto com os seguintes atributos timestamp, status, errorMessage. E em vez de tu ter o metodo getExceptionBody, tu teria o build para construir o objeto da classe ResponseDto. Por fim retornaria algo como ResponseEntity<ResponseDto>.

2022-08-30 09:21 UTC, alexsrosa approved these changes

2022-08-30 09:21 UTC, alexsrosa commented on src/main/java/com/mindera/pizza/exceptions/GlobalExceptionHandler.java
> +    private Map<String, String> getExceptionBody(Exception e, HttpStatus status) {
nice

2022-08-30 10:44 UTC, merged